### ISSUE TITLE
config: CLASSIFIER_VALID_SEPARATORS not found

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-classifier#4]
The following line https://github.com/inveniosoftware/invenio-classifier/blob/master/invenio_classifier/keyworder.py#L39

Gives an error:
```
KeyError: ‘CLASSIFIER_VALID_SEPARATORS’
```

Using `lambda` to access the config might help.

**Comment by jalavik** [comment]
This is due to `invenio_classifier` missing in `PACKAGES`. If you add it there it should be all right.

**Comment by jmartinm** [comment]
True, thanks!
